awenarum/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^contact/', include('contactform.urls')),
    url(r'^', include('home.urls')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contactform/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.contact_page, name='contact_page.html')
]

home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'

urlpatterns = [
    # /
    url(r'^$', views.index, name='index'),

    # /article/[article_id]
    url(r'^article/(?P<article_id>[0-9]+)/$', views.article, name='article'),
]

contactform/models.py
from django.db import models
from django.forms import ModelForm


class Message(models.Model):
    REQUEST = 'R'
    QUERY = 'Q'
    FEEDBACK = 'F'
    OTHER = 'O'
    MESSAGE_TYPE_CHOICES = (
        (REQUEST, 'Request'),
        (QUERY, 'Query'),
        (FEEDBACK, 'Feedback'),
        (OTHER, 'Other')
    )
    email = models.CharField(max_length=50)
    message_type = models.CharField(
        max_length=30, choices=MESSAGE_TYPE_CHOICES)
    message = models.TextField()


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['email', 'message_type', 'message']

home/models.py
from django.db import models


class HomepageArticle(models.Model):
    title = models.CharField(max_length=30)
    subtitle = models.CharField(max_length=100)
    text = models.TextField()
    image = models.FileField()

    def __str__(self):
        return self.title + ' - ' + self.subtitle

contactform/forms.py
from django import forms
from contactform.models import Message


class MessageForm(forms.Form):
    email = forms.CharField(max_length=50)
    message_type = forms.ChoiceField(
        choices=Message.MESSAGE_TYPE_CHOICES, widget=forms.RadioSelect())

contactform/views.py
from django.shortcuts import render_to_response
from django.template import RequestContext


def contact_page(request):
    return render_to_response(
        'contactform/contact_page.html', context_instance=RequestContext(
            request))

home/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404

from . models import HomepageArticle


def index(request):
    articles = HomepageArticle.objects.all()
    return render(request, 'home/index.html', {'articles': articles})


def article(request, article_id):
    article = get_object_or_404(HomepageArticle, pk=article_id)
    return render(request, 'home/article.html', {'article': article})

awenarum/templates/awenarum/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/awenarum.css">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <title>Awen Arum</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script src="{{ STATIC_URL }}scripts/masonry.pkgd.min.js"></script>
    {% block extra_head %}
    {% endblock %}
</head>
<body>
    <div class="container">
        <div class="header">
            {% include "awenarum/nav.html" %}
        </div>
        <div class="content">
            {% block content %}
            {% endblock %}
        </div>
        <div class="footer">
            <div class="contact">
                <p><span class="contact_type">Tel:&nbsp;</span><span class="contact_value"><a href="tel:01460894523">01460&nbsp;894523</a></span></p>
                <p><span class="contact_type">Email:&nbsp;</span><span class="contact_value"><a href="mailto:info@awen-arum.com">info@awen-arum.com</a></span></p>
                <p><a href="mailto:luke@lukeshiner.com">&copy;Luke Shiner {% now "Y" %}</a></p>
            </div>
        </div>
    </div>
    <script>
        $(window).on("load", function() {
            $(".articles").masonry({
                itemSelector: 'article',
            })
        })
    </script>
</body>
</html>

awenarum/templates/awenarum/nav.html
<a href="/"><div class="header_logo"></div></a>
<div class="sitename">
    <h1>Awen Arum</h1>
    <h3>Homemade Skincare</h3>
</div>
<div class="navigation">
    <a class="navitem" id="active" href="/">Home</a>
    <a class="navitem" href="/store">Store</a>
    <a class="navitem" href="/contact">Contact</a>
</div>

contactform/templates/contactform/contact_form.html
<form action="" class="contact_form" id="contact_form" type="post">
    <table class="contact_form">
        <tr>
            <td><label for="email_address">Email Address: </label></td>
            <td><input type="email" name="email_address" size="40"></td>
        </tr>
        <tr>
            <td><label for="message_type">Message Type: </label></td>
            <td>
                <input type="radio" name="message_type" value="request">Request<br>
                <input type="radio" name="message_type" value="query">Query<br>
                <input type="radio" name="message_type" value="feedback">Feedback<br>
                <input type="radio" name="message_type" value="other">other<br>
            </td>
        </tr>
        <tr>
            <td><label for="message_box">Message: </label></td>
            <td><textarea name="message_box" rows="8" cols="40"></textarea></td>
        </tr>
        <tr>
            <td></td>
            <td><input type="submit" value="Submit"></td>
        </tr>
    </table>
</form>

contactform/templates/contactform/contact_page.html
{% extends "awenarum/base.html" %}
{% block extra_head %}
<link rel="stylesheet" href="{{ STATIC_URL }}contactform/css/contactform.css">
{% endblock %}
{% block content %}
<h3>Contact</h3>
{% include "contactform/contact_form.html" %}
{% endblock %}

home/templates/home/article.html
{% extends "awenarum/base.html" %}

{% block content %}
<h1>{{ article.title }}</h1>
<h2>{{ article.subtitle }}</h2>
{{ article.text | linebreaks}}
{% endblock %}

home/templates/home/index.html
{% extends "awenarum/base.html" %}

{% block content %}
{% if articles %}
    <div class="articles">
        {% for article in articles %}
            <article class="mainpage_article">
                <a href="{% url 'home:article' article.id %}"><h2>{{ article.title }}</h2></a>
                <h4>{{ article.subtitle }}</h4>
                <img src="{{ article.image.url }}" alt="image" height="200">
                {{ article.text | linebreaks }}
            </article>
        {% endfor %}
    </div>
{% else %}

{% endif %}
{% endblock %}

home/templates/home/loremshort.html
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut egestas aliquam scelerisque. Donec nec ipsum nisi. Fusce lacus velit, mattis ut aliquet eget, ultrices ac lorem. Vestibulum consectetur luctus laoreet. Praesent egestas est sed ipsum congue, vitae hendrerit ex dignissim. Aliquam convallis, augue sit amet lobortis accumsan, elit leo accumsan ligula, at faucibus augue libero vel neque. Aenean auctor consectetur pellentesque.</p>
<p>Ut neque augue, faucibus non massa vel, tincidunt faucibus est. Nullam vulputate lacinia lacus id condimentum. Maecenas quam arcu, euismod sit amet pretium eu, mattis ut est. Aliquam ac viverra diam. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In pellentesque pretium ligula at ultricies. Cras efficitur tellus id diam viverra, ut bibendum mauris tristique. Vivamus cursus nibh a mauris consectetur, pharetra facilisis leo efficitur. Ut vitae purus dignissim, maximus odio a, ultricies ante. Proin nec accumsan velit. Sed eget mauris rhoncus, vehicula nisl eget, vestibulum magna.</p>
<img src="http://financial-style.com/wp-content/uploads/2015/12/organicskincare1-563x353.jpg" alt="image" height="200">
<p>Nulla id bibendum mi. Fusce ipsum dui, viverra a magna nec, dictum sagittis elit. Morbi ipsum enim, dapibus et justo in, fringilla hendrerit ligula. Suspendisse efficitur risus quis libero fermentum lacinia. Mauris condimentum consequat hendrerit. Maecenas nec augue risus. Nulla facilisi. Pellentesque hendrerit venenatis augue, sed interdum sapien facilisis quis. Vestibulum eget auctor turpis. Nulla in elementum purus.</p>
<p>Donec pretium lorem risus, et pretium ligula mattis eleifend. Morbi feugiat tortor et velit maximus, eu aliquet turpis condimentum. Aliquam tristique, velit quis dapibus scelerisque, risus est mattis tellus, vel semper orci magna eu magna. Nam placerat urna in nunc euismod interdum. Etiam mattis rhoncus diam eu lobortis. Duis sodales diam eget est accumsan, id laoreet eros consectetur. Vestibulum eu augue vulputate, congue mauris a, rhoncus sapien. Sed sit amet consectetur purus. Donec justo nunc, aliquam sit amet leo sit amet, vestibulum ornare quam. Donec ut ipsum ante. Vestibulum id felis consequat, semper ipsum feugiat, dictum ipsum. Sed rhoncus nulla non lacus facilisis, at egestas tortor scelerisque.</p>

home/templates/home/loremshort2.html
<p>Ut neque augue, faucibus non massa vel, tincidunt faucibus est. Nullam vulputate lacinia lacus id condimentum. Maecenas quam arcu, euismod sit amet pretium eu, mattis ut est.</p>
<img src="http://www.beautyholicsanonymous.com/beautyholics/wp-content/uploads/2015/11/natural-skincare.jpg" alt="image" height="200">
<p>Nulla id bibendum mi. Fusce ipsum dui, viverra a magna nec, dictum sagittis elit. Morbi ipsum enim, dapibus et justo in, fringilla hendrerit ligula. Suspendisse efficitur risus quis libero fermentum lacinia. Mauris condimentum consequat hendrerit.</p>
<p>Donec pretium lorem risus, et pretium ligula mattis eleifend. Morbi feugiat tortor et velit maximus, eu aliquet turpis condimentum. Aliquam tristique, velit quis dapibus scelerisque, risus est mattis tellus, vel semper orci magna eu magna. Nam placerat urna in nunc euismod interdum. </p>

home/templates/home/loremshort3.html
<p>Ut neque augue, faucibus non massa vel, tincidunt faucibus est. Nullam vulputate lacinia lacus id condimentum. Maecenas quam arcu, euismod sit amet pretium eu, mattis ut est.</p>
<img src="http://simg.sulekha.com/go-natural-with-your-skin/thumbnailfull/go-natural-with-your-skin-2011-11-15-4-44-38.jpg" alt="image" height="200">
<p>Nulla id bibendum mi. Fusce ipsum dui, viverra a magna nec, dictum sagittis elit. Morbi ipsum enim, dapibus et justo in, fringilla hendrerit ligula. Suspendisse efficitur risus quis libero fermentum lacinia. Mauris condimentum consequat hendrerit.</p>
<p>Donec pretium lorem risus, et pretium ligula mattis eleifend. Morbi feugiat tortor et velit maximus, eu aliquet turpis condimentum. Aliquam tristique, velit quis dapibus scelerisque, risus est mattis tellus, vel semper orci magna eu magna. Nam placerat urna in nunc euismod interdum. </p>